---
title: 'Reproducible Research: Project Assignment 1'
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Loading and preprocessing the data
```
setwd("C:/Users/user/Documents/Coursera/Data Science")
Data <- read.csv(file="activity.csv", header=TRUE)
Sys.setlocale("LC_TIME", "English")
library(lattice)
```
##What is mean total number of steps taken per day?
```
total <- aggregate(steps ~ date, Data, FUN=sum)
```
####Total steps illustration as histogram
```
hist(total$steps,
      main = "Total Steps/Day",
      xlab = "days",
      col="blue")
```
####Calculate and report the mean and median total number of steps taken per day

```
mean_var <- mean(total$steps, na.rm = TRUE)
median_var <- median(total$steps, na.rm = TRUE)
```

##What is the average daily activity pattern?

####Time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
```
mean_intervals <- tapply(Data$steps, Data$interval, mean, na.rm = TRUE)
plot(row.names(mean_intervals),
      mean_intervals,
      type = "l",
      xlab = "5 minutes intervals",
      ylab = "All days average",
      main = "Average number of steps taken by days",
      col = "blue")
```

####Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
```
max_intervals <- which.max(mean_intervals)
names(max_intervals)
```

##Imputing missing values

####Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with s)
```
NAs <- sum(is.na(Data))
NAs
```
####new dataset that is equal to the original dataset but with the missing data filled in
```
newData <- Data
Mean_by_interval <- aggregate(steps ~ interval, data = newData, FUN = mean)

for (i in 1:nrow(newData)){
    if (is.na(newData$steps[i])) {
        newData$steps[i] <- Mean_by_interval$steps[which(newData$interval[i] == Mean_by_interval$interval)]
    }
}
```
####Make a histogram of the total number of steps

```
total_mean <- aggregate (steps ~ date, data = newData, FUN = sum)
hist(total_mean$steps,
      main = "Total Steps/Day",
      xlab = "days",
      col="blue")
```
####report the mean and median total number of steps taken per day
```
newMeanSteps <- mean(newData$steps)
newMedianSteps <- median(newData$steps)
```
####values differ from the estimates from the first part of the assignment
```
mean_diff <- mean_var - newMeanSteps
median_diff <- median_var - newMedianSteps
total_diff <- sum(newData$steps) - sum(total$steps)
```


##Are there differences in activity patterns between weekdays and weekends?
#### Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.
```
newData["Day_type"] <- "NA"

for (i in 1:nrow(newData)){
    if (as.character(weekdays(as.Date(newData$date[i]))=="Saturday")) {
        newData$Day_type[i] <- "weekend"
    } 
    else { if (as.character(weekdays(as.Date(newData$date[i]))=="Sunday")) {
                newData$Day_type[i] <- "weekend"
    }
          else {
                newData$Day_type[i] <- "weekday"
    }
    }
}

```

####panel plot containing a time series plot (i.e. ) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days 
```
Mean_by_interval_daytype <- aggregate(steps ~ interval + Day_type, data = newData, FUN = mean)

xyplot(steps ~ interval | Day_type, data = Mean_by_interval_daytype, type="l", grid = TRUE)

```
